import styles from '@test/styles/Home.module.css'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import { useState } from 'react'
import { OnResultFunction, QrReader } from 'react-qr-reader'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    const [qrData, setQrData] = useState<string[]>([])

    const handleScan: OnResultFunction = (result, error, codeReader) => {
        console.log(codeReader)

        if (result) {
            const resultText = result?.getText()
            setQrData((prevData) =>
                !prevData.includes(resultText) ? [...prevData, resultText] : prevData
            )
        }

        if (error) {
            console.error(error)
        }
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <QrReader
                    onResult={handleScan}
                    scanDelay={1000}
                    constraints={{ facingMode: 'user' }}
                    containerStyle={{ width: '100%' }}
                    videoContainerStyle={{ width: '100%' }}
                />

                {qrData.map((qr, index) => (
                    <li key={index}>{qr}</li>
                ))}
            </main>
        </>
    )
}
